# Generated by Django 6.0.2 on 2026-02-19 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_options_remove_expense_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settlement',
            options={},
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='settled_at',
        ),
        migrations.AddField(
            model_name='settlement',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.group'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
